### ISSUE TITLE
Compiler options are not comparable

### ISSUE THREAD

**Issue by ufechner7** [nordlow/compiler-benchmark#17]
If you want to compare the compilation times of gcc and Julia the compiler optimization options should be comparable.

Julia is running by default with -O2, gcc by default with -O0

The benchmarks should either use -O2 for gcc or the option --compile=min for Julia.

**Comment by nordlow** [comment]
Ahh, thanks! I'll update. Hang on!

**Comment by nordlow** [comment]
For

`./benchmark --languages=D:dmd,Julia --function-count=50 --function-depth=50`

this gives a 5x speedup. Thanks.

**Comment by PallHaraldsson** [comment]
Since you merged this, and are ok with it, i.e. the porpose of the benchmark to time fastest (debug) build(?) then, then can you change the readme too? E.g. "100280.5x" looks bad.

I would like -O0 in Julia to actually mean no optimization. The other option means the interpreter is used (I still think "compiled", i.e. then LLVM bitcode interpreted, not sure, but very much doubt the source code itself is interpreted, e.g. in a loop).
